#
# Questions
#
questions:
  CUSTOMER: 'Name des Kunden (e.g. Deutsches Weininstitut GmbH)'
  ABBREVIATION: 'Kunden-Kürzel (e.g. dwi)'
  PROJECT_NAME: 'Projekt-Name (e.g. webs-dwi-typo3-website)'
  WEBSITE: 'Website URL (e.g. www.deutscheweine.de)'
  LINK_TECH_DOKU: 'Link zur Technischen Dokumentation (Confluence)'
  GIT_REPO_URL: 'Git-Repository (e.g. git@git.xima.de:opensource/webs-dwi-typo3-XXX.git)'

#
# Substitutions
#
substitutions:
  - './README.md'
  - './htdocs/typo3/.env.dev.dist'
  - './htdocs/typo3/.env.dist'
  - './.ddev/config.yaml'
  - './.ddev/apache/layout.conf'
  - './.ddev/README.md'
  - './sonar-project.properties'
