image: composer:latest
cache:
  paths:
    - .composer-cache/
before_script:
  - composer config -g cache-dir "$(pwd)/.composer-cache"

stages:
  - build
  - test
  - deploy
  - sync

build-php:
  stage: build
  script:
    - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/

build-node:
  stage: build
  image: misterio92/ci-php-node
  cache:
    paths:
      - .npm/
  before_script: [ ]
  script:
    - npm ci --unsafe-perm
    - npm run build
    - npm run build:patternlab
  artifacts:
    paths:
      - packages/xm_dkfz_net_prototype/Resources/Public

test-php-lint:
  stage: test
  script:
    - composer run ci:php:lint

test-php-cs-fixer:
  stage: test
  needs: [ "build-php" ]
  script:
    - composer run ci:php:fixer

test-php-stan:
  stage: test
  needs: [ "build-php" ]
  script:
    - composer run ci:php:stan

.deploy-prepare:
  stage: deploy
  needs: [ "build-php" ]
  before_script:
    - apk add --quiet rsync gzip
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $TYPO3_STAGING_URL >> ~/.ssh/known_hosts
    - if [[ ! -z "$TYPO3_PRODUCTION_URL" ]]; then ssh-keyscan $TYPO3_PRODUCTION_URL >> ~/.ssh/known_hosts; fi
    - chmod 644 ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\n" > ~/.ssh/config

deploy-xima-staging:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-php-stan" ]
  stage: deploy
  only:
    refs:
      - "master"
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  script:
    - vendor/bin/dep deploy-fast staging

deploy-dkfz-staging:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node" ]
  stage: deploy
  rules:
    - if: $IS_SCHEDULED_BACKUP == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" && $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep deploy:unlock staging-dkfz
    - vendor/bin/dep deploy-fast staging-dkfz

deploy-dkfz-production:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-php-stan" ]
  stage: deploy
  rules:
    - if: $IS_SCHEDULED_BACKUP == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" && $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep deploy:unlock production-dkfz
    - vendor/bin/dep deploy production-dkfz

reset-staging-dkfz:
  extends: .deploy-prepare
  stage: sync
  only:
    variables:
      - $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep db:copy production-dkfz --options=target:staging-dkfz --no-interaction
    - vendor/bin/dep media:copy production-dkfz --options=target:staging-dkfz --no-interaction
  when: manual

backup-production-dkfz:
  extends: .deploy-prepare
  stage: sync
  only:
    variables:
      - $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep db:export production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction
    - vendor/bin/dep db:download production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction
    - vendor/bin/dep db:process --options=dumpcode:BackupProductionDkfz --no-interaction
    - vendor/bin/dep db:compress --options=dumpcode:BackupProductionDkfz --no-interaction
    #- vendor/bin/dep media:pull production-dkfz --no-interaction
  artifacts:
    paths:
      - .dep/database
      - public/fileadmin
      - public/uploads

reset-staging-xima:
  extends: .deploy-prepare
  stage: sync
  only:
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  when: manual
  script:
    - 'curl --location --output artifacts.zip --header "PRIVATE-TOKEN: $DKFZ_ACCESS_TOKEN" "https://git.dkfz.de/api/v4/projects/69/jobs/artifacts/master/download?job=backup-production-dkfz"'
    - ls -la
    - unzip -o artifacts.zip
    - vendor/bin/dep db:decompress staging --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:upload staging --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:import staging --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep media:push staging --no-interaction -vvv

#deploy-feature:
#  extends: .deploy-prepare
#  only:
#    refs:
#      - "/^DKFZ-.*$/"
#    variables:
#      - $GITLAB_LOCATION == "XIMA-INTERN"
#  script:
#    - vendor/bin/dep deploy-fast feature -o branch=$CI_COMMIT_BRANCH
