workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" || $CI_COMMIT_BEFORE_SHA != '0000000000000000000000000000000000000000'

variables:
  BASE_BRANCH: "master"
  project_webserver: "t3-debian11-01"
  project_database: "t3-mariadb10-5-01"
  project_aliases: "handbuch"
  project_php_version: "8.1"
  project_goaccess: "true"
  downstream_pipeline_branch: major-1.x.x

default:
  image:
    name: composer:2.6.6@sha256:ea36c4cb064eb5d9ec04dd38a9c6480791ec64c9cfc9e1fd22b2fa0b00b5ce81
    pull_policy: if-not-present

stages:
  - build
  - test
  - provision
  - deploy
  - sync

include:
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/build-php.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/build-node.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/test-php-lint.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/test-php-cs-fixer.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/test-php-stan.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/test-xml-lint.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/test-yaml-lint.yml'
  - 'https://raw.githubusercontent.com/xima-media/gitlab-templates/main/.deploy-prepare.yml'
  - project: 'typo3/intern/devops/sys-t3-ansible-management'
    file:
      - 'gitlab-templates/manage-environment.yml'
    rules:
      - if: $GITLAB_LOCATION != 'XIMA-INTERN'
        when: never
      - if: $CI_COMMIT_BRANCH == "master"
      - if: $CI_COMMIT_BRANCH == "development"
      - if: $CI_COMMIT_BRANCH =~ /^DKFZ-.*$/
      - if: $CI_COMMIT_BRANCH =~ /^DIS-.*$/

build-node:
  image:
    name: node:18-slim@sha256:8d6134753fa4bc1d3b2dd23e1e32c484b8c6bddbe09f60125aad8026fa4b1d91
  artifacts:
    paths:
      - packages/xm_dkfz_net_site/Resources/Public/Css/dist
      - packages/xm_dkfz_net_site/Resources/Public/JavaScript/dist

deploy-dkfz-staging:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-xml-lint", "test-php-stan" ]
  stage: deploy
  environment:
    name: DKFZ Stage
    url: https://intranetstage.dkfz.de/
  rules:
    - if: $IS_SCHEDULED_BACKUP == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "development" && $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep deploy:unlock staging-dkfz -vvv
    - vendor/bin/dep deploy-fast staging-dkfz -vvv

deploy-dkfz-production:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-xml-lint", "test-php-stan" ]
  stage: deploy
  when: manual
  environment:
    name: DKFZ Live
    url: https://intranet.dkfz.de/
  rules:
    - if: $IS_SCHEDULED_BACKUP == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" && $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep deploy:unlock production-dkfz -vvv
    - vendor/bin/dep deploy production-dkfz -vvv

reset-staging-dkfz:
  extends: .deploy-prepare
  needs: [ "build-php", "backup-production-dkfz" ]
  stage: sync
  rules:
    - if: $GITLAB_LOCATION == 'DKFZ-INTERN'
  script:
    - vendor/bin/dep reset:from_production_artifact -o DKFZ_ACCESS_TOKEN=$DKFZ_ACCESS_TOKEN staging-dkfz -vvv --no-interaction
  when: manual

backup-production-dkfz:
  extends: .deploy-prepare
  stage: sync
  rules:
    - if: $GITLAB_LOCATION == 'DKFZ-INTERN'
  script:
    - vendor/bin/dep db:export production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:process production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:compress production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:download production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep media:pull production-dkfz --no-interaction
  artifacts:
    paths:
      - .dep/database
      - public/fileadmin
      - public/uploads
    expire_in: 1 day

reset:xima-testing:
  extends: .deploy-prepare
  stage: sync
  when: manual
  rules:
      - if: $GITLAB_LOCATION != 'XIMA-INTERN'
        when: never
      - if: $CI_COMMIT_BRANCH == "master"
      - if: $CI_COMMIT_BRANCH == "development"
      - if: $CI_COMMIT_BRANCH =~ /^DKFZ-.*$/
      - if: $CI_COMMIT_BRANCH =~ /^DIS-.*$/
  script:
    - vendor/bin/dep reset:from_production_artifact -o DKFZ_ACCESS_TOKEN=$DKFZ_ACCESS_TOKEN dev-t3-debian11-01-${BRANCH_ID,,} -vvv --no-interaction
