variables:
  BASE_BRANCH: "master"
  project_webserver: "t3-debian11-01"
  project_database: "t3-mariadb10-5-01"
  project_name: $CI_PROJECT_NAME
  project_branch: $CI_COMMIT_BRANCH
  project_base_branch: $BASE_BRANCH
  project_aliases: "handbuch"
  project_php_version: "8.1"
  project_goaccess: "true"
  project_redis: "false"
  project_scheduler_frequency_minutes: "15"
  project_delete: "false"
  downstream_pipeline_branch: major-1.x.x

default:
  image:
    name: composer:2.6.5@sha256:e4b813199694949b2d9edb4873056af647fa3e45b58439f525db428282ba2c4d
    pull_policy: if-not-present

stages:
  - build
  - test
  - provision
  - deploy
  - sync

include:
  - project: 'typo3/intern/devops/gitlab-templates'
    file:
      - build-php.yml
      - build-node.yml
      - test-php-lint.yml
      - test-php-cs-fixer.yml
      - test-php-stan.yml
      - test-xml-lint.yml
      - .deploy-prepare.yml
  - project: 'typo3/intern/devops/sys-t3-ansible-management'
    file:
      - 'gitlab-templates/manage-environment.yml'
    rules:
      - if: $GITLAB_LOCATION == 'XIMA-INTERN'
      - if: $CI_COMMIT_BRANCH == "master"
      - if: $CI_COMMIT_BRANCH == "development"
      - if: $CI_COMMIT_BRANCH =~ /^DKFZ-.*$/
      - if: $CI_COMMIT_BRANCH =~ /^DIS-.*$/

build-node:
  image:
    name: node:16@sha256:c94b82f9827cab6e421b350965a9ef11b25b13ffbd1030536203d541f55dcbe2
  artifacts:
    paths:
      - packages/xm_dkfz_net_site/Resources/Public/Css/dist
      - packages/xm_dkfz_net_site/Resources/Public/JavaScript/dist

deploy-xima-testing:
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-php-stan", "test-xml-lint", "provision-environment" ]

deploy-dkfz-staging:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-xml-lint", "test-php-stan" ]
  stage: deploy
  environment:
    name: DKFZ Stage
    url: https://intranetstage.dkfz.de/
  rules:
    - if: $IS_SCHEDULED_BACKUP == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "development" && $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep deploy:unlock staging-dkfz
    - vendor/bin/dep deploy-fast staging-dkfz -vvv

deploy-dkfz-production:
  extends: .deploy-prepare
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-xml-lint", "test-php-stan" ]
  stage: deploy
  when: manual
  environment:
    name: DKFZ Live
    url: https://intranet.dkfz.de/
  rules:
    - if: $IS_SCHEDULED_BACKUP == "true"
      when: never
    - if: $CI_COMMIT_BRANCH == "master" && $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep deploy:unlock production-dkfz
    - vendor/bin/dep deploy production-dkfz -vvv

reset-staging-dkfz:
  extends: .deploy-prepare
  needs: [ "build-php", "backup-production-dkfz" ]
  stage: sync
  only:
    variables:
      - $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep reset:from_production_artifact -o DKFZ_ACCESS_TOKEN=$DKFZ_ACCESS_TOKEN staging-dkfz --no-interaction
  when: manual

backup-production-dkfz:
  extends: .deploy-prepare
  stage: sync
  only:
    variables:
      - $GITLAB_LOCATION == "DKFZ-INTERN"
  script:
    - vendor/bin/dep db:export production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:process production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:compress production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep db:download production-dkfz --options=dumpcode:BackupProductionDkfz --no-interaction -vvv
    - vendor/bin/dep media:pull production-dkfz --no-interaction
  artifacts:
    paths:
      - .dep/database
      - public/fileadmin
      - public/uploads
    expire_in: 1 day

reset:xima-staging:
  extends: .deploy-prepare
  stage: sync
  only:
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  when: manual
  script:
    - vendor/bin/dep reset:from_production_artifact -o DKFZ_ACCESS_TOKEN=$DKFZ_ACCESS_TOKEN dev-t3-debian11-01-${BRANCH_ID,,} --no-interaction
