image: composer:latest
cache:
  paths:
    - .composer-cache/
before_script:
  - composer config -g cache-dir "$(pwd)/.composer-cache"

stages:
  - build
  - test
  - deploy

build-php:
  stage: build
  script:
    - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/

build-node:
  stage: build
  image: misterio92/ci-php-node
  cache:
    paths:
      - .npm/
  before_script: [ ]
  script:
    - npm ci --unsafe-perm
    - npm run build
    - npm run build:patternlab
  artifacts:
    paths:
      - packages/xm_dkfz_net_prototype/Resources/Public

test-php-lint:
  only:
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  stage: test
  script:
    - composer run ci:php:lint

test-php-cs-fixer:
  only:
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  stage: test
  needs: [ "build-php" ]
  script:
    - composer run ci:php:fixer

test-php-stan:
  only:
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  stage: test
  needs: [ "build-php" ]
  script:
    - composer run ci:php:stan

.deploy-prepare:
  stage: deploy
  needs: [ "build-php", "build-node", "test-php-lint", "test-php-cs-fixer", "test-php-stan" ]
  before_script:
    - apk add --quiet rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan dkfz-typo3-dev.xima.local >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\n" > ~/.ssh/config

deploy-staging:
  extends: .deploy-prepare
  only:
    refs:
      - "master"
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  script:
    - vendor/bin/dep deploy-fast staging
  environment:
    name: staging
    url: https://stage.dkfz-typo3-dev.xima.local/

deploy-staging-dkfz:
  stage: deploy
  needs: [ "build-php" ]
  only:
    refs:
      - "master"
    variables:
      - $GITLAB_LOCATION == "DKFZ-INTERN"
  before_script:
    - apk add --quiet rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" >> | tr -d '\r' > ~/.ssh/id_rsa
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan intracmsstage.dkfz-heidelberg.de >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -V
    - cat ~/.ssh/known_hosts
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n\n" > ~/.ssh/config
    - cat ~/.ssh/config
    - ls -la ~/.ssh/
    - cat ~/.ssh/id*
    - ssh xima@intracmsstage "echo $PATH"
  script:
    - vendor/bin/dep deploy-fast staging-dkfz -vvv
  environment:
    name: staging
    url: https://intracmsstage.dkfz-heidelberg.de/

deploy-feature:
  extends: .deploy-prepare
  only:
    refs:
      - "/^DKFZ-.*$/"
    variables:
      - $GITLAB_LOCATION == "XIMA-INTERN"
  script:
    - vendor/bin/dep deploy-fast feature -o branch=$CI_COMMIT_BRANCH
