image: composer:latest
cache:
  paths:
    - .composer-cache/
before_script:
  - composer config -g cache-dir "$(pwd)/.composer-cache"
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

stages:
  - build
  - test
  - deploy

build-php:
  stage: build
  script:
      - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/

build-node:
  stage: build
  image: node:latest
  cache:
    paths:
      - .npm/
  before_script: []
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - packages/xm_dkfz_net_prototype/Resources/Public

test-php-cs-fixer:
  stage: test
  needs: ["build-php"]
  script:
    - composer run ci:php:fixer

test-php-stan:
  stage: test
  needs: ["build-php"]
  script:
    - composer run ci:php:stan

deploy-staging:
  stage: deploy
  needs: ["test-php-cs-fixer", "test-php-stan"]
  script:
    - vendor/bin/dep deploy-fast staging
