image: composer:latest
cache:
  paths:
    - .composer-cache/
before_script:
  - composer config -g cache-dir "$(pwd)/.composer-cache"

stages:
  - build
  - test

build-php:
  stage: build
  script:
      - composer install --ignore-platform-reqs --optimize-autoloader --no-ansi --no-interaction --no-progress
  artifacts:
    paths:
      - vendor/

build-node:
  stage: build
  image: node:latest
  cache:
    paths:
      - .npm/
  before_script: []
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - packages/xm_dkfz_net_prototype/Resources/Public

test-php-cs-fixer:
  stage: test
  script:
    - composer run ci:php:fixer

test-php-stan:
  stage: test
  script:
    - composer run ci:php:stan

test-acceptance:
  stage: test
  script:
    - sudo apt-get -qq update && sudo apt-get -qq -y install libnss3-tools
    - curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh\n
    - ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent
    - ddev start
    - ddev exec vendor/bin/codecept run acceptance -d -c Tests/codeception.yml
