services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Blueways\BwGuild\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Blueways\BwGuild\Controller\BackendController:
    tags: ['backend.controller']

  Blueways\BwGuild\EventListener\ModifyListTable:
    tags:
      - name: event.listener
        identifier: 'bw-guild/modify-list-table'
