services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmManual\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmManual\Preview\MtextPreviewRenderer:
    public: true
