name: Build and release TYPO3 extension

on: [ push ]

jobs:
  release:
    if: github.ref == 'refs/heads/development'
    uses: maikschneider/reusable-workflows/.github/workflows/release-typo3-extension.yml@main
    secrets:
      teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
    with:
      base-branch: main
