services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmDkfzNetSite\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmDkfzNetSite\EventListener\UserSearchEvent:
    tags:
      - name: event.listener
        identifier: 'userSearchEvent'

  Xima\XmDkfzNetSite\EventListener\UserEditFormEvent:
    tags:
      - name: event.listener
        identifier: 'userEditFormEvent'

  Xima\XmDkfzNetSite\EventListener\InitializeUserUpdateAction:
    tags:
      - name: event.listener
        identifier: 'initializeUserUpdateAction'

  Xima\XmDkfzNetSite\EventListener\UserInfoApiEvent:
    tags:
      - name: event.listener
        identifier: 'userInfoApiEvent'

  Xima\XmDkfzNetSite\EventListener\NewsDetailAction:
    tags:
      - name: event.listener
        identifier: 'newsDetailAction'

  Xima\XmDkfzNetSite\Hook\DrawHeaderHook:
    public: true

  Xima\XmDkfzNetSite\Hook\DrawFooterHook:
    public: true

  Xima\XmDkfzNetSite\Preview\TeaserPreviewRenderer:
    public: true

  Xima\XmDkfzNetSite\DataProcessing\TeaserProcessor:
    public: true

  Xima\XmDkfzNetSite\DataProcessing\PageContactsProcessor:
    public: true

  Xima\XmDkfzNetSite\Command\ImportFeUserCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importFeUser'
        schedulable: false
    arguments:
      $groupRepository: '@Xima\XmDkfzNetSite\Domain\Repository\UserGroupRepository'
      $userRepository: '@Xima\XmDkfzNetSite\Domain\Repository\UserRepository'

  Xima\XmDkfzNetSite\Command\ImportPlaceCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importPlace'
        schedulable: false
    arguments:
      $groupRepository: '@Xima\XmDkfzNetSite\Domain\Repository\UserGroupRepository'
      $userRepository: '@Xima\XmDkfzNetSite\Domain\Repository\PlaceRepository'

  Xima\XmDkfzNetSite\Command\ImportFeUserGroupCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importFeUserGroup'
        schedulable: false
    arguments:
      $groupRepository: '@Xima\XmDkfzNetSite\Domain\Repository\UserGroupRepository'
      $userRepository: '@Xima\XmDkfzNetSite\Domain\Repository\UserRepository'

  Xima\XmDkfzNetSite\Command\ImportBeUserCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importBeUser'
        schedulable: false
    arguments:
      $userRepository: '@Xima\XmDkfzNetSite\Domain\Repository\BeUserRepository'
      $groupRepository: '@Xima\XmDkfzNetSite\Domain\Repository\BeGroupRepository'

  Xima\XmDkfzNetSite\Command\ImportBeGroupCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importBeUserGroup'
        schedulable: false
    arguments:
      $groupRepository: '@Xima\XmDkfzNetSite\Domain\Repository\BeGroupRepository'
      $userRepository: '@Xima\XmDkfzNetSite\Domain\Repository\BeUserRepository'

  Xima\XmDkfzNetSite\Command\ImportDbMountPointsCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importDbMountPointsCommand'
        schedulable: false

  Xima\XmDkfzNetSite\Command\SlugUpdaterCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:updateSlugs'
        schedulable: true

  Xima\XmDkfzNetSite\Command\ImportAllCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:import'
        schedulable: true

  Xima\XmDkfzNetSite\Utility\PhoneBookUtility:
    public: true

  Blueways\BwGuild\Controller\ApiController:
    arguments:
      $userRepository: '@Xima\XmDkfzNetSite\Domain\Repository\UserRepository'
