services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmDkfzNetSite\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmDkfzNetSite\EventListener\BackendUserLookup:
    tags:
      - name: event.listener
        identifier: 'oauthBeUserRegistration'

  Xima\XmDkfzNetSite\EventListener\FrontendUserLookup:
    tags:
      - name: event.listener
        identifier: 'oauthFeUserRegistration'

  querybuilder.beUsers:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'be_users'

  Xima\XmDkfzNetSite\UserFactory\BackendUserFactory:
    public: true
    arguments:
      - '@querybuilder.beUsers'

  Xima\XmDkfzNetSite\Hook\DrawHeaderHook:
    public: true

  Xima\XmDkfzNetSite\Preview\TeaserPreviewRenderer:
    public: true

  Xima\XmDkfzNetSite\DataProcessing\TeaserProcessor:
    public: true

  Xima\XmDkfzNetSite\Command\ImportFeUserCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importFeUser'
        schedulable: false

  Xima\XmDkfzNetSite\Command\ImportFeUserGroupCommand:
    tags:
      - name: 'console.command'
        command: 'dkfz:importFeUserGroup'
        schedulable: false

  Xima\XmDkfzNetSite\Utility\PhoneBookUtility:
    public: true
