services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmDkfzNetSite\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmDkfzNetSite\EventListener\BackendUserLookup:
    tags:
      - name: event.listener
        identifier: 'oauthUserRegistration'
