
Das vorliegende Handbuch liefert eine allgemeine Einführung zum Umgang mit dem Content Management System (CMS) TYPO3 für Redakteure. Die ersten Kapitel beschreiben dabei projektunabhängig die TYPO3 Version 11, während sich die daran anschließenden Kapitel sechs und sieben auf projektspezifische Besonderheiten beziehen. Im letzten Kapitel Glossar finden Sie eine Übersicht über die geläufigsten Symbole und deren Bedeutung im Backend aufgelistet.

IMPORTANT: Das Handbuch ist als Nachschlagewerk konzipiert, um den Redakteur bestimmte Fragen zu beantworten. Deshalb gibt es an manchen Stellen Dopplungen, die bei chronologischem Durcharbeiten des Handbuchs nicht notwendig wären

=== Was ist TYPO3?
TYPO3 ist ein Open-Source Content-Management-System. Open-Source bedeutet, dass der Quelltext für jeden frei verfügbar ist und von jedem für seinen Zwecke abgeändert werden kann. TYPO3 ist hauptsächlich in der Programmiersprache PHP geschrieben. Die Entwicklung wurde 1997 von Kasper Skårhøj begonnen und wird seit 2001 als Open-Source Projekt von vielen Entwicklern vorangetrieben. Mittlerweile ist die aktuelle Long-Term-Support-Version TYPO3 11.5 LTS.


=== Die Begriffe "Backend" und "Frontend"
Mit dem Begriff "Backend" wird die Benutzeroberfläche bezeichnet, in welcher verschiedene Aufgaben zur Konfiguration der Webseite erledigt werden können. Darunter fallen beispielsweise das Anlegen, Berabeiten und Löschen von einzelnen Seiten oder das Hinzufügen von Bildern und verschiedenen Inhaltselementen.
Der Begriff "Frontend" meint hingegen die Webseite an sich. Also das, was der Besucher sieht, wenn er eine bestimmte Seite ansteuert.

=== Der Cache
TYPO3 verwendet verschiedene Caches. Caches sind Zwischenspeicher, die bestimmte Daten abspeichern, da ansonsten bei jeder Verwendung eine Neuberechnung notwendig wäre. So werden beispielsweise die Inhalte einer bestimmten Seite zwischengespeichert, um zu verhindern, dass für jeden neuen Besucher der Seite neu berechnent werden muss, welche Inhalte die Seite anzeigen soll. Daher kann es manchmal notwendig sein, den Frontend-Cache zu löschen, damit eine Änderung an den Inhaltselementen auch angezeigt wird.

=== Optimale Browser

Grundsätzlich kann das Backend in folgenden, aktuellen Versionen der Browser betrieben werden:

* Chrome
* Firefox
* Safari
* Mircosoft Edge

Am empfehlenswertesten sind dabei die aktuellsten Versionen von Chrome und Firefox, da diese erfahrungsgemäß am wenigsten Probleme verursachen.



