base: /
baseVariants:
  -
    base: 'https://manual.xm-dkfz-net.ddev.site/'
    condition: 'getenv("DDEV_PROJECT") == "xm-dkfz-net"'
enabled_oauth2_providers: ''
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
    languageId: 0
    enabled_oauth2_providers: ''
    oauth2_callback_slug: ''
    oauth2_storage_pid: ''
luxletterUnsubscribePid: '1'
oauth2_callback_slug: ''
oauth2_storage_pid: ''
rootPageId: 108
websiteTitle: ''
