services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmGoaccess\Widgets\:
    resource: '../Classes/Widgets/*'

  dashboard.widget.xm_goaccess_uniqueVisitors:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@Xima\XmGoaccess\Widgets\Provider\UniqueVisitorsDataProvider'
      #$buttonProvider: '@Xima\XmGoaccess\Widgets\Provider\UniqueVisitorsButtonProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'goaccessUniqueVisitors'
        groupNames: 'goaccess'
        title: 'LLL:EXT:xm_goaccess/Resources/Private/Language/locallang.xlf:widgets.uniqueVisitors.title'
        description: 'LLL:EXT:xm_goaccess/Resources/Private/Language/locallang.xlf:widgets.uniqueVisitors.description'
        iconIdentifier: 'content-widget-rss'
        height: 'medium'
        width: 'medium'
