services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tpwd\KeSearchPremium\:
    resource: '../Classes/*'

  Tpwd\KeSearchPremium\EventListener\RegisterBoostKeywordColumn:
    tags:
      - name: event.listener
        identifier: 'registerBoostKeywordColumn'
        event: Tpwd\KeSearch\Event\MatchColumnsEvent

  Tpwd\KeSearchPremium\EventListener\IndexPartialWords:
    tags:
      - name: event.listener
        identifier: 'indexPartialWords'
        event: Tpwd\KeSearch\Event\ModifyFieldValuesBeforeStoringEvent
