#!/bin/bash

## Description: Executes 'composer' commands in 'htdocs/layoutbuilder'
## Usage: composer:layoutbuilder
## Example: "ddev composer:layoutbuilder [OPTIONS]"

COMMAND=$@

if [[ -n "${COMMAND// /}" ]]; then
  echo
  echo -e '\033[94m[INFO]\033[m Run command:\033[93m composer' $COMMAND '-d "htdocs/layoutbuilder" \033[m'
  composer $COMMAND -d "htdocs/layoutbuilder"
else
  echo
  echo -e '\033[94m[INFO]\033[m Install dependencies from lock file'
  composer install -d "htdocs"

  echo
  echo -e '\033[94m[INFO]\033[m Check for updates'
  composer update -d "htdocs/layoutbuilder" --dry-run

  echo
  read -p $'\e[93m[CONFIG]\e[m Update composer dependencies? [Y/n] (no):' UPDATE
  if [[ $UPDATE =~ ^[Yy]$ ]]
  then
    echo -e '\033[94m[INFO]\033[m Update dependencies'
    composer update -d "
    /layoutbuilder"
  fi
fi
echo
echo -e '\033[92mDone.\033[m'
