#!/bin/bash

## Description: Executes 'composer' commands in 'htdocs/typo3'
## Usage: composer:app
## Example: "ddev composer:app [OPTIONS]"

COMMAND=$@

if [[ -n "${COMMAND// /}" ]]; then
  echo
  echo -e '\033[94m[INFO]\033[m Run command:\033[93m composer' $COMMAND '-d "htdocs/typo3" \033[m'
  composer $COMMAND -d "htdocs/typo3"
else
  echo
  echo -e '\033[94m[INFO]\033[m Install dependencies from lock file'
  composer install -d "htdocs/typo3"

  echo
  echo -e '\033[94m[INFO]\033[m Check for updates'
  composer update -d "htdocs/typo3" --dry-run

  echo
  read -p $'\e[93m[CONFIG]\e[m Update composer dependencies? (y|N):' UPDATE
  if [[ $UPDATE =~ ^[Yy]$ ]]
  then
    echo -e '\033[94m[INFO]\033[m Update dependencies'
    composer update -d "htdocs/typo3"
  fi
fi
echo
echo -e '\033[92mDone.\033[m'
