#!/bin/bash

## Description: Run typo3cms (https://packagist.org/packages/helhum/typo3-console) in cli
## Usage: console
## Example: "ddev console [OPTIONS]"

php /var/www/html/htdocs/typo3/bin/typo3cms $@
