#!/bin/bash

## Description: Install and initialize local TYPO3 instance
## Usage: init
## Example: ddev init
echo
read -p $'\e[95m[CONFIG]\e[m Initialize TYPO3 instanz? (y/n)[n] ' INIT_TYPO3
read -p $'\e[95m[CONFIG]\e[m Sync database (prod-to-local)? (y/n)[n] ' SYNC_DB
read -p $'\e[95m[CONFIG]\e[m Build assets? (y/n)[n] ' INSTALL_ASSETS

if [[ $INIT_TYPO3 =~ ^[Yy]$ ]]
then
    echo -e "\033[94m[INFO]\033[m Install TYPO3"
    cd /var/www/html/htdocs/typo3
    composer install
    php bin/typo3cms install:setup --no-interaction
    echo -e "\033[92m[OK]\033[m TYPO3 installed"
fi

if [[ $SYNC_DB =~ ^[Yy]$ ]]
then
    echo -e "\033[94m[INFO]\033[m Install deployment tools"
    cd /var/www/html/htdocs
    composer install
    echo -e "\033[94m[INFO]\033[m Sync Prod database into local database"
    db_sync_tool -f /var/www/html/deployment/db-sync-tool/sync-prod-to-local.json
    php htdocs/typo3/bin/typo3cms database:updateschema
    echo -e "\033[92m[OK]\033[m Deployment tools installed"
fi

if [[ $INSTALL_ASSETS =~ ^[Yy]$ ]]
then
    echo -e "\033[94m[INFO]\033[m Install assets"
    cd /var/www/html/htdocs/
    npm ci
    grunt staging
    echo -e "\033[92m[OK]\033[m Assets installed"
fi
echo
echo -e '\033[92mDone.\033[m'
