#!/bin/bash

## Description: Create a new app version
## Usage: release
## Example: "ddev release 1.3.0-rc1"

version=$@
composerPath="htdocs/typo3"
# Check if given version correspond to the semver guidelines
if [[ $version =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
  echo -e "\033[94m[Info]\033[m Adjust composer.json and generate composer.lock"
  # Update property "version"
  composer config version $version -d "$composerPath"
  # Generate new composer.lock file to keep the composer files valid
  composer update nothing -d "$composerPath" -q --no-scripts

  # Distinguish between Release Candidate and Release
  if [[ $version == *"rc"* ]]; then
    note="Build"
  else
    note="Release"
  fi
  # Print possible git commit message
  echo -e "\033[92m[$note]\033[m Version $version"
else
  echo -e "\033[91m[Failure]\033[m Given version '$version' not matching semantic version constraints"
fi
