#!/bin/bash

## Description: Executes 'sync.py' in htdocs
## Usage: sync
## Example: "ddev sync [SYSTEM]"

sys=$@
if [ -z "${sys}" ]
  then
    sys="prod"
fi

db_sync_tool -f /var/www/html/deployment/db-sync-tool/sync-${sys}-to-local.json
php htdocs/typo3/bin/typo3cms database:updateschema
