#!/bin/bash

## Description: Executes 'tail' command on typo3 log file in htdocs/typo3/web/typo3temp/var/logs
## Usage: tail
## Example: ddev tail
cd "htdocs/typo3/web/typo3temp/var/logs"
latest_file=$(find . -not -name "*_deprecations_*" -type f)
tail $@ $latest_file
