#!/bin/bash

## Description: Run patternlab commands inside the web container
## Usage: theme
## Example: "ddev patternlab start, ddev patternlab watch"

# start patternLab
if [[ $@ == "init" ]]
then
  echo -e '\e[32m ╔═══════════════════════════════════════╗\e[0m'
  echo -e '\e[32m ║                                       ║\e[0m'
  echo -e '\e[32m ║     \e[97mPatternLab will be installed.\e[32m     ║\e[0m'
  echo -e '\e[32m ║                                       ║\e[0m'
  echo -e '\e[32m ╚═══════════════════════════════════════╝\e[0m'

  echo 'Installing frontend dependencies ...'
  cd /var/www/html/htdocs/prototype/ && npm ci
  echo 'Installing patternLab dependencies ...'
  cd /var/www/html/htdocs/prototype/patternlab/ && npm ci
elif [[ $@ == "start" ]]
then
  echo -e '\e[32m ╔═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗\e[0m'
  echo -e '\e[32m ║                                                                                                                                                       ║\e[0m'
  echo -e '\e[32m ║     \e[97mPrototype is available after the build from https://dkfz-intranet-prototype.ddev.site:3001 or https://dkfz-intranet-prototype.ddev.site:3000.\e[32m     ║\e[0m'
  echo -e '\e[32m ║                                                                                                                                                       ║\e[0m'
  echo -e '\e[32m ╚═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝\e[0m'
  cd /var/www/html/htdocs/prototype/patternlab/ && npm run serve
elif [[ $@ == "build" || $@ == "prototype" ]]
then
  echo -e '\e[32m ╔════════════════════════════════════════════╗\e[0m'
  echo -e '\e[32m ║                                                                                                                                                  ║\e[0m'
  echo -e '\e[32m ║     \e[97mPrototype is watching.\e[32m     ║\e[0m'
  echo -e '\e[32m ║                                                                                                                                                  ║\e[0m'
  echo -e '\e[32m ╚════════════════════════════════════════════╝\e[0m'
  cd /var/www/html/htdocs/prototype/patternlab/ && npm run serve
# watching the frontend
elif [[ $@ == "watch" ]]
then
  echo -e '\e[32m ╔═══════════════════════════════════╗\e[0m'
  echo -e '\e[32m ║                                   ║\e[0m'
  echo -e '\e[32m ║     \e[97mPrototype is watching ...\e[32m     ║\e[0m'
  echo -e '\e[32m ║                                   ║\e[0m'
  echo -e '\e[32m ╚═══════════════════════════════════╝\e[0m'
  cd /var/www/html/htdocs/prototype/ && npm run watch
# watching the frontend
elif [[ $@ == "typo3" || $@ == "app" || $@ == "staging" ]]
then
  echo -e '\e[32m ╔═══════════════════════════════════╗\e[0m'
  echo -e '\e[32m ║                                   ║\e[0m'
  echo -e '\e[32m ║     \e[97mTYPO3 is building!       \e[32m     ║\e[0m'
  echo -e '\e[32m ║                                   ║\e[0m'
  echo -e '\e[32m ╚═══════════════════════════════════╝\e[0m'
  cd /var/www/html/htdocs/prototype/ && npm run staging
# every npm in patternLab dir
elif [[ $@ == "fix" || $@ == "fix-styles" ]]
then
  echo -e '\e[32m ╔═══════════════════════════════════╗\e[0m'
  echo -e '\e[32m ║                                   ║\e[0m'
  echo -e '\e[32m ║     \e[97mFixing SCSS ...         \e[32m   ║\e[0m'
  echo -e '\e[32m ║                                   ║\e[0m'
  echo -e '\e[32m ╚═══════════════════════════════════╝\e[0m'
  cd /var/www/html/htdocs/prototype/ && npm run fix-styles
else
   cd /var/www/html/htdocs/prototype/patternlab/ && $@
fi
