services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmDkfzNetEvents\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XmDkfzNetEvents\Command\CacheEventsCommand:
    tags:
      - name: 'console.command'
        command: 'events:cache'
        schedulable: true
    arguments:
      $cache: '@cache.pages'
