services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmDkfzNetEvents\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.event_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'xmdkfznetevents_eventcache' ]

  Xima\XmDkfzNetEvents\Utility\EventLoaderUtility:
    arguments:
      $cache: '@cache.event_cache'
