services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaTwitterClient\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XimaTwitterClient\Command\FetchTweetsCommand:
    tags:
      - name: 'console.command'
        command: 'twitter:fetchTweets'
        schedulable: true

  Xima\XimaTwitterClient\FetchType\LatestTweets:
    public: true
