version: '3.6'

services:
  selenium:
    container_name: ddev-${DDEV_SITENAME}-chrome
    image: seleniarm/standalone-chromium:latest
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=4444
    external_links:
      - ddev-router:$DDEV_HOSTNAME
