services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XmDkfzNetJobs\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  cache.job_cache:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: [ '@TYPO3\CMS\Core\Cache\CacheManager', 'getCache' ]
    arguments: [ 'xmdkfznetjobs_jobcache' ]

  Xima\XmDkfzNetJobs\Command\CacheJobsCommand:
    tags:
      - name: 'console.command'
        command: 'jobs:cache'
        schedulable: true

  Xima\XmDkfzNetJobs\Utility\JobLoaderUtility:
    arguments:
      $cache: '@cache.job_cache'
