base: '%env("TYPO3_BASE_URL")%'
baseVariants:
  -
    base: '%env("TYPO3_RELEASE_URL")%'
    condition: 'getenv("IS_RELEASE_REQUEST")'
enabled_oauth2_providers: 'xima,dkfz'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-de
    direction: ltr
    flag: de
    websiteTitle: ''
  -
    title: English
    enabled: true
    base: /en
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    websiteTitle: ''
    navigationTitle: English
    hreflang: en-US
    direction: ''
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
luxletterUnsubscribePid: '160'
oauth2_callback_slug: login
oauth2_storage_pid: 91
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: ''
    map:
      preview.html: 1560777975
      newsletter.html: 1562349004
      pixel.png: 1561894816
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\n"
websiteTitle: 'DKFZ Intranet'
imports:
  -
    resource: 'EXT:bw_guild/Configuration/Routing/Api.yaml'
  -
    resource: 'EXT:bw_guild/Configuration/Routing/Userlist.yaml'
  -
    resource: 'EXT:xm_dkfz_net_site/Configuration/Routing/News.yaml'
